[develop] <-- [feature/86byem6yf] First PR
Pawlitka/NoteApp pull request #1
Opened 2024-05-27 14:40 UTC by Pawlitka

2024-05-30 14:08 UTC, Cozoob requested changes

2024-05-30 14:08 UTC, Cozoob commented on styles.css
> +    --mauve-color: #D4ABEF;
well... you might name it purpole. We developers are simple men...

2024-05-30 14:08 UTC, Cozoob commented on script.js
> +let notes = document.querySelectorAll(".input-box");
Please remove it... I can clearly see that not only it should be
 `const NOTES = ...`
 but also the variable as global is used nowhere.

2024-05-30 14:08 UTC, Cozoob commented on index.html
> +    <meta name="viewport" content="width=device=width, initial-scale=1.0">
Please fix the naming...
`content="width=device-width, initial-scale=1.0"`

**device-width**

More [here](https://www.w3schools.com/css/css_rwd_viewport.asp), to learn.

2024-05-30 14:08 UTC, Cozoob commented on index.html
> +        <h1><img src="images/notes.png" alt="notes.png">Notes</h1>
I would not put anything inside text tags such as span,p,h1,h2 etc... if you want to have a block that contains "Notes" and image and is consider as one box... use extra div :):

```html
        <div>
            <img src="images/notes.png" alt="notes.png">
            <h1>
                Notes
            </h1>
        </div>
``` 

Please notice also my way of formatting

2024-05-30 14:08 UTC, Cozoob commented on index.html
> +    </div>
Yeah... more about formatting all, isn't it better?:

```html
<body>
    <div class="container">
        <div>
            <img src="images/notes.png" alt="notes.png">
            <h1>
                Notes
            </h1>
        </div>
        <button class="create-button">
            <img src="images/edit.png" alt="edit.png">
            Create Notes
        </button>
        <div class="notes-container">
        </div>
    </div>
</body>
```

2024-05-30 14:08 UTC, Cozoob commented on script.js
> +showNotes()
Well I would mobe this function at the end of the file... since your first function that is always fired when initiliazing the website is 'showNotes'

2024-05-30 14:08 UTC, Cozoob commented on script.js
> +showNotes()
I would even say it violates Single Responsibility :O LOOK! It not only set notes to inner Html (show notes) but also it loads/gets them! (localStorage.getItem) ...!!!! So make extra function named getNotes that will return localStorage.getItem("notes");

```javascript
const LOCAL_STORAGE_NOTES_KEY = "notes";
// some code...

function getNotes() {
    return localStorage.getItem(LOCAL_STORAGE_NOTES_KEY);
}

function showNotes() {
    NOTES_CONTAINER.innerHTML = getNotes();
}
``` 

Notice that I created new const, for key value of the local storage :) If you do not know how maps work and what local storage is... please watch tutorials...

2024-05-30 14:08 UTC, Cozoob commented on script.js
> +    localStorage.setItem("notes", NOTES_CONTAINER.innerHTML);
please use new const for key value when setting value for that key in localStorage :)

2024-05-30 14:08 UTC, Cozoob commented on script.js
> +})
```javascript
// better version :) step by step
// First step please us extra function for handling event.
// use const value for at least img source
const DELETE_IMAGE_SOURCE = 'images/delete.png';

// some code

CREATE_BUTTON.addEventListener('click', handleCreateNote);

function handleCreateNote() {
    let inputBox = document.createElement("p");
    let img = document.createElement("img");
    inputBox.className = "input-box";
    inputBox.setAttribute("contenteditable", "true");
    img.src = DELETE_IMAGE_SOURCE;
    NOTES_CONTAINER.appendChild(inputBox).appendChild(img);
}

// Second step please extract logic from handler function:
// you can prepare input box and img and return input box with already added
// img as child :) it is much more readable
const DELETE_IMAGE_SOURCE = 'images/delete.png';

// some code

CREATE_BUTTON.addEventListener('click', handleCreateNote);

function handleCreateNote() {
    let noteBlock = prepareNoteBlock();
    NOTES_CONTAINER.appendChild(noteBlock);
}

// Notice how I even seperated actions for image creating and inputBox creating =?=> note block creating?
// what else you can notice ;) ... I will give answer in step 3
function prepareNoteBlock() {
    let img = document.createElement("img");
    img.src = DELETE_IMAGE_SOURCE;
    
    let inputBox = document.createElement("p");
    inputBox.className = "input-box";
    inputBox.setAttribute("contenteditable", "true");
    
    inputBox.appendChild(img);
    return inputBox;
}

// Third step... seperate logic for creating delete img and inputBox in prepareNoteBlock
// and maybe we should call prepareNoteBlock as prepareNoteElement ;) it is better
const DELETE_IMAGE_SOURCE = 'images/delete.png';

// some code

CREATE_BUTTON.addEventListener('click', handleCreateNote);

function handleCreateNote() {
    let noteElement = prepareNoteElement();
    NOTES_CONTAINER.appendChild(noteElement);
}

function prepareNoteElement() {
    const img = createDeleteImageElement();
    
    let inputBox = createInputBoxElement();
    inputBox.appendChild(img);
    
    return inputBox;
}

function createDeleteImageElement() {
    let img = document.createElement("img");
    img.src = DELETE_IMAGE_SOURCE;
    return img;
}

function createInputBoxElement() {
    let inputBox = document.createElement("p");
    inputBox.className = "input-box";
    inputBox.setAttribute("contenteditable", "true");
    return inputBox;
}
```

2024-05-30 14:08 UTC, Cozoob commented on script.js
> +})
Please try to do the same as we did in CREATE_BUTTON :)

2024-05-30 14:08 UTC, Cozoob commented on script.js
> +})
Please try to do the same as we did in CREATE_BUTTON :)

2024-06-01 11:07 UTC, Pawlitka commented on styles.css
> +    --mauve-color: #D4ABEF;
rename it to easier understand :)

2024-06-01 11:16 UTC, Pawlitka commented on index.html
> +    <meta name="viewport" content="width=device=width, initial-scale=1.0">
now its correct.

2024-06-01 12:00 UTC, Pawlitka commented on script.js
> +let notes = document.querySelectorAll(".input-box");
program is screaming to use let instead of const

2024-06-01 12:04 UTC, Pawlitka commented on index.html
> +        <h1><img src="images/notes.png" alt="notes.png">Notes</h1>
Yeah, it looks better. I separete img from h1.

2024-06-01 12:10 UTC, Pawlitka commented on index.html
> +    </div>
Done!!

2024-06-01 13:59 UTC, Pawlitka commented on script.js
> +})
Done!!

2024-06-02 16:19 UTC, Cozoob approved these changes

2024-06-02 16:48 UTC, merged